apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-node-metrics-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-node-metrics-app
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_requests_total_per_second
      target:
        type: AverageValue
        averageValue: 10 # Target 10 requests per second per pod
