# prometheus-adapter-values.yaml
prometheus:
  url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local
  port: 9090

rules:
  default: true
  custom:
    - seriesQuery: '{__name__="http_requests_total",namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
